apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: example-deployment
spec:
  replicas: 3
  selector:
    app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example-container
        image: your-registry.com/your-image:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: your-volume
          mountPath: /path/to/mount
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullSecrets:
        - name: your-image-pull-secret
      volumes:
      - name: your-volume
        emptyDir: {}
      - name: your-pvc-volume
        persistentVolumeClaim:
          claimName: your-pvc-name
